name: advanced_flutter
description: "Advanced Flutter"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.0-323.2.beta

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  faker: ^2.1.0
  mockito: ^5.4.4
  build_runner: ^2.4.12
  http: ^1.2.2
  mocktail: ^1.0.4
  dartx: ^1.2.0
  rxdart: ^0.28.0
  network_image_mock: ^2.1.1
  awesome_flutter_extensions: ^1.2.0
  flutter_cache_manager: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
